services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: guide
      # POSTGRES_USER: guide  # Uncomment if you want a specific user
      # POSTGRES_PASSWORD: guide  # Uncomment if you want a specific user password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
